name: CI/CD 

on: 
  push: 
    branches:
      - hosting

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Hostinger VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with: 
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USER}}
          key: ${{secrets.VPS_SSH_KEY}}
          script: |
            cd /root/websites/aicorp/FL-Aidna-Backend
            git pull origin main
            npm install --production
            pm2 restart aidna-backend
            pm2 save